# PLOT TRIP - Plot a taxi trip on a Google map

library(ggmap)
library(ggplot2)

# GET TRIP MAP - For the supplied trip model, retrieve a map for showing it.
#
# Parameters:
#  -  model: result of analysis of one or more trips as generated by taxi.knn.
#  -  zoom: optional tweak (positive to zoom in, negative to zoom out)
#         in case the default map size is not appealing
#
# Result:
#  -  A map, derived from Google, of the area in which the taxi trips happened.
#
# Get Trip Map tries to return a map with enough margin around the trip zone to
# plot error zones such as large circles showing, e.g., 90% confidence intervals.

get.trip.map = function( model, zoom=0 ) {
  lon.range <- range( model$lon.act )
  lat.range <- range( model$lat.act )
  lon.adjust <- cos( mean( lat.range ))
  locat <- c( mean(lon.range), mean(lat.range) )
  span <- max( (lon.range[2]-lon.range[1])*lon.adjust, 
                lat.range[2]-lat.range[1], 
                1e-4 )
  goog.zoom <- floor( zoom + 8 - log(span,2) )
  print( paste( "Span(degrees): ", span, ", Google zoom: ", goog.zoom, sep="" ))
  map <- get_map( location=locat, zoom=goog.zoom, maptype="roadmap", scale=1 )
  map <- ggmap( map, extent="panel" )
  map
}

# PLOT TRIP For a given trip, plot the trip's progress on the map.
#
# Parameters:
#  -  map: 
#  -  model: result of analysis of one trip as generated by taxi.knn
#  -  index: index of snapshot time -
#        index = 0: show start and end points of the trip
#        index > 0: show trip at (index-1)/4 minutes into the trip
#        index < 0: show trip at (index-1)/4 minutes before the end of the trip
#  -  title: title for the plot
#  -  point.scale: factor to control relative size of start/end points,
#  -  circle.scale: factor to control relative size of circle of confidence
#
# Note that you have to manually adjust the circle.scale to suit the displayed
# size of the plot. For example, if you expand the plot window to twice the 
# height and width, you need to double the circle.scale. It normally takes
# some experimentation to make it accurate.

plot.trip = function( map, model, index=0, title="Porto Taxi", point.scale=1, circle.scale=1 ) {
  if (index < 0) index <- nrow(model) + 1 + index
  intvl <- model[index,"intvl"]
  title <- paste( title,
                  "     Trip", model[1,"trip.id"],
                  "     Minute", formatC( model[max(1,index),"intvl"], digits=2, format="f" ),
                  sep=" " )
  map.1 <- map +
    ggtitle( title ) +
    theme( plot.title=element_text(size=rel(1.5)) )
  if (index > 0) {
    map.1 <- map.1 +
      geom_path( data=model[1:index,], aes(x=lon.act,y=lat.act),
                 size=point.scale, color="blue" ) +
      geom_point( data=model[index,], aes(x=lon.pred,y=lat.pred),
                  size=circle.scale*120*model[index,"pred.range"],
                  color="red", alpha=0.25 ) +
      geom_point( data=model[index,], aes(x=lon.act,y=lat.act),
                  size=3*point.scale, color="blue", shape=16 ) +
      geom_point( data=model[index,], aes(x=lon.pred,y=lat.pred), 
                  size=3*point.scale, color="yellow", shape=16 )  }
  map.1 <- map.1 +
    geom_point( data=model[1,], aes(x=lon.act,y=lat.act),
                size=3*point.scale, color="forestgreen", shape=15 ) +
    geom_point( data=model[nrow(model),], aes(x=lon.act,y=lat.act),
                size=3*point.scale, color="red", shape=17 )
  map.1
}
